### PR TITLE
code-html-tag-added

### PR DESCRIPTION
**Pull request by Ndaboom**
A code HTML tag has been added to the index.html file with "Hello World" as content.

### CODE REVIEW

**Review by levy002 — CHANGES_REQUESTED** [review]
## Hello @Ndaboom  , :wave:
### I'm Levy, your PR reviewer

Good job so far :+1: 
There are some issues that you still need to work on to go to the next project but you are almost there!



## Status: REQUIRED CHANGES ♻️
_Check the comments under the review._

- [x] Kindly make sure to set up linters correctly so it runs to check if there are no errors on your pull request. I recommend you take a step back and read this[ lesson](https://github.com/microverseinc/linters-config/blob/master/html-css) to understand it clearly and follow the guideline to set it correctly.

- [x] Kindly make to have  `test.md` file with the text "This file should be ignored by git". and make sure that it is ignored by git (means it can't be seen on our repo).

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- [x] Kindly make sure to write your commits messages more professionally.  I recommend you take a step back and read this[ lesson](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md) to understand it deeply.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @levy002 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Ndaboom** [comment]
Hi @levy002, 

Just updated the code but there is still one point that not passing the linters test, is there anything I need to know? And the last thing that I need to know is If I should submit another review request in the Microverse dashboard.

Thanks!

**Review by Reem-lab — CHANGES_REQUESTED** [review]
# Hi @Ndaboom, 👋🏻👋🏻

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
- Good commit messages ✅
- Descriptive pull request ✅

 ## Required Changes ♻️
_Check the comments under the review._
- [x] I think you didn't add the files for stylelint and webhint for testing the linters so kindly add them since they have the rules for organizing your code. and Don't foget to install the packages 🚀✅🙏🏻check this link [here](https://github.com/microverseinc/linters-config/tree/master/html-css)
image
## If you scroll down you can see how to install their packages then you can run commands to check if there is any error 🙏🏻🚀

- [x] Please fix the stylelint linters by using this command `npx stylelint "**/*.{css,scss}"` you can see all the error in you style file then you can fix it, then run it again till it fixed 🙏🏻🔥🔥

image


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by ridwanediallo — APPROVED** [review]
## Hi @Ndaboom 👋, 
CelebrateHappyGIF (2)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- No linter errors ✔️ 
- Meaningful  commit messages  ✔️ 
- Descriptive pull request ✔️

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
